In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
import scipy.stats as stats

In [ ]:
df = pd.read_csv('/content/test_1.csv')

In [ ]:
df.head()

ID  age            job   marital  education default  balance housing  \
0  38441   32       services   married  secondary      no      118     yes   
1  40403   78        retired  divorced    primary      no     2787      no   
2   3709   31  self-employed    single   tertiary      no      144     yes   
3  37422   57       services    single    primary      no     3777     yes   
4  12527   45    blue-collar  divorced  secondary      no     -705      no   

  loan    contact  day month  duration  campaign  pdays  previous poutcome  
0   no   cellular   15   may        20         6     -1         0  unknown  
1   no  telephone    1   jul       372         1     -1         0  unknown  
2   no    unknown   16   may       676         1     -1         0  unknown  
3   no  telephone   13   may        65         2     -1         0  unknown  
4  yes    unknown    3   jul       111         1     -1         0  unknown

In [ ]:
df.tail()

ID  age          job  marital  education default  balance housing  \
13559  23465   39   management  married   tertiary      no       45      no   
13560  11743   54  blue-collar  married    primary      no     2281     yes   
13561  28292   35      retired  married    primary      no      285     yes   
13562  45163   29       admin.   single  secondary      no      464      no   
13563  34839   29       admin.  married  secondary      no        2     yes   

      loan   contact  day month  duration  campaign  pdays  previous poutcome  
13559   no  cellular   28   aug       148         4     -1         0  unknown  
13560   no   unknown   20   jun       158         1     -1         0  unknown  
13561   no  cellular   29   jan       136         1     -1         0  unknown  
13562   no  cellular    9   nov       208         2     91         3  success  
13563   no  cellular    6   may       339         1    362         1  failure

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13564 entries, 0 to 13563
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   ID         13564 non-null  int64 
 1   age        13564 non-null  int64 
 2   job        13564 non-null  object
 3   marital    13564 non-null  object
 4   education  13564 non-null  object
 5   default    13564 non-null  object
 6   balance    13564 non-null  int64 
 7   housing    13564 non-null  object
 8   loan       13564 non-null  object
 9   contact    13564 non-null  object
 10  day        13564 non-null  int64 
 11  month      13564 non-null  object
 12  duration   13564 non-null  int64 
 13  campaign   13564 non-null  int64 
 14  pdays      13564 non-null  int64 
 15  previous   13564 non-null  int64 
 16  poutcome   13564 non-null  object
dtypes: int64(8), object(9)
memory usage: 1.8+ MB


In [ ]:
df.describe()

ID           age       balance           day      duration  \
count  13564.000000  13564.000000  13564.000000  13564.000000  13564.000000   
mean   22704.057726     40.887128   1358.496535     15.738646    258.278679   
std    12994.043329     10.604108   3082.940623      8.288174    258.488648   
min        1.000000     18.000000  -3313.000000      1.000000      0.000000   
25%    11546.000000     33.000000     71.000000      8.000000    102.000000   
50%    22782.000000     39.000000    445.000000     16.000000    180.000000   
75%    33974.250000     48.000000   1413.250000     21.000000    319.000000   
max    45206.000000     95.000000  98417.000000     31.000000   3253.000000   

           campaign         pdays      previous  
count  13564.000000  13564.000000  13564.000000  
mean       2.759510     41.648555      0.594441  
std        3.060928    101.985178      1.998193  
min        1.000000     -1.000000      0.000000  
25%        1.000000     -1.000000      0.000000  
50%        2.000000     -1.000000      0.000000  
75%        3.000000     -1.000000      0.000000  
max       58.000000    850.000000     55.000000

In [ ]:
df.isnull().sum()

ID           0
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
dtype: int64

In [ ]:
df.drop_duplicates()

ID  age            job   marital  education default  balance  \
0      38441   32       services   married  secondary      no      118   
1      40403   78        retired  divorced    primary      no     2787   
2       3709   31  self-employed    single   tertiary      no      144   
3      37422   57       services    single    primary      no     3777   
4      12527   45    blue-collar  divorced  secondary      no     -705   
...      ...  ...            ...       ...        ...     ...      ...   
13559  23465   39     management   married   tertiary      no       45   
13560  11743   54    blue-collar   married    primary      no     2281   
13561  28292   35        retired   married    primary      no      285   
13562  45163   29         admin.    single  secondary      no      464   
13563  34839   29         admin.   married  secondary      no        2   

      housing loan    contact  day month  duration  campaign  pdays  previous  \
0         yes   no   cellular   15   may        20         6     -1         0   
1          no   no  telephone    1   jul       372         1     -1         0   
2         yes   no    unknown   16   may       676         1     -1         0   
3         yes   no  telephone   13   may        65         2     -1         0   
4          no  yes    unknown    3   jul       111         1     -1         0   
...       ...  ...        ...  ...   ...       ...       ...    ...       ...   
13559      no   no   cellular   28   aug       148         4     -1         0   
13560     yes   no    unknown   20   jun       158         1     -1         0   
13561     yes   no   cellular   29   jan       136         1     -1         0   
13562      no   no   cellular    9   nov       208         2     91         3   
13563     yes   no   cellular    6   may       339         1    362         1   

      poutcome  
0      unknown  
1      unknown  
2      unknown  
3      unknown  
4      unknown  
...        ...  
13559  unknown  
13560  unknown  
13561  unknown  
13562  success  
13563  failure  

[13564 rows x 17 columns]

In [ ]:
age=[32,78,31,57,45,39,54,35,29,29]

In [ ]:
len(age)

10

In [ ]:
age_mode=df["age"].mode()
age_mode

0    32
Name: age, dtype: int64

In [ ]:
import numpy as np
sample=np.random.choice(age,10)
sample

array([78, 78, 35, 32, 39, 78, 31, 54, 32, 29])

In [ ]:
from scipy.stats import ttest_1samp

In [ ]:
ttest,p_value=ttest_1samp(sample,age_mode)

In [ ]:
ttest

2.446236884736541

In [ ]:
p_value

0.036984320961869696

In [ ]:
if p_value < 0.05:
    print('Reject Null Hypothesis')
else:
    print('Fail to reject Null Hypothesis')

Reject Null Hypothesis


In [8]:
# One More Example - 1 sample t test

In [7]:
import numpy as np
import math
import scipy.stats as stats
np.random.seed(8)

In [9]:
school_age=stats.poisson.rvs(loc=0,mu=40,size=400)
classA_age=stats.poisson.rvs(loc=0,mu=40,size=200)

In [ ]:
#Null Hypothesis: There is no difference between population Mean and Sample mean
#Alternative Hypothesis: There is difference between popultaion Mean and Sample mean
#alpha value =5%

#p value < 0.05 Reject the null Hypothesis
#p value > 0.05 Fail to reject Null Hypothesis

In [10]:
school_age

array([48, 35, 39, 40, 41, 45, 42, 37, 32, 28, 38, 38, 53, 39, 46, 28, 46,
       39, 33, 34, 41, 53, 42, 40, 39, 33, 42, 36, 47, 44, 47, 48, 36, 40,
       47, 53, 33, 41, 46, 32, 35, 30, 39, 34, 39, 40, 47, 42, 33, 43, 49,
       37, 26, 41, 41, 39, 46, 33, 35, 41, 41, 52, 35, 42, 35, 42, 42, 33,
       44, 42, 37, 36, 38, 33, 33, 38, 36, 49, 34, 35, 41, 46, 52, 52, 33,
       50, 48, 56, 44, 43, 43, 38, 39, 45, 44, 40, 37, 45, 39, 44, 41, 37,
       47, 37, 33, 38, 42, 43, 42, 36, 44, 34, 38, 32, 46, 37, 39, 42, 37,
       40, 37, 33, 26, 29, 57, 44, 39, 46, 37, 49, 38, 42, 41, 36, 32, 33,
       33, 38, 54, 37, 45, 40, 40, 47, 37, 45, 29, 44, 37, 43, 38, 32, 53,
       39, 52, 43, 43, 40, 40, 30, 43, 35, 40, 38, 40, 38, 40, 42, 48, 36,
       37, 37, 40, 45, 42, 49, 35, 34, 30, 40, 40, 41, 37, 44, 44, 43, 33,
       38, 45, 33, 41, 36, 47, 32, 42, 40, 45, 48, 43, 37, 37, 32, 31, 46,
       33, 27, 51, 37, 30, 49, 38, 47, 44, 37, 32, 27, 40, 35, 52, 30, 37,
       40, 34, 39, 36, 47

In [11]:
classA_age

array([52, 26, 28, 36, 38, 44, 48, 36, 52, 39, 36, 26, 49, 38, 42, 50, 34,
       43, 35, 43, 31, 42, 43, 37, 40, 39, 45, 48, 38, 48, 39, 37, 44, 39,
       44, 41, 41, 26, 41, 33, 25, 36, 40, 36, 43, 40, 41, 47, 46, 40, 34,
       34, 31, 41, 38, 43, 53, 46, 38, 39, 40, 42, 36, 34, 33, 40, 39, 36,
       37, 40, 32, 38, 54, 41, 30, 52, 30, 46, 32, 57, 41, 42, 37, 43, 39,
       35, 42, 44, 44, 41, 45, 43, 37, 36, 46, 43, 35, 44, 32, 46, 45, 50,
       39, 38, 42, 45, 43, 49, 36, 38, 38, 39, 31, 51, 37, 42, 43, 61, 38,
       29, 44, 41, 46, 39, 30, 35, 43, 46, 43, 49, 29, 40, 36, 43, 39, 37,
       38, 35, 37, 22, 36, 34, 34, 46, 42, 38, 42, 43, 28, 40, 44, 43, 43,
       43, 33, 47, 36, 40, 38, 41, 39, 38, 45, 34, 38, 34, 33, 43, 36, 36,
       39, 40, 39, 40, 36, 35, 48, 35, 29, 49, 52, 39, 39, 27, 37, 42, 43,
       49, 38, 42, 45, 46, 33, 45, 44, 41, 41, 29, 44, 41])

In [12]:
school_age.mean()

39.945

In [13]:
classA_age.mean()

39.83

In [15]:
from scipy.stats import ttest_1samp

ttest, p_value = ttest_1samp(classA_age, school_age.mean())

In [16]:
p_value

0.7920808762846049

In [18]:
if p_value < 0.05:
    print('Reject Null Hypotesis')
else:
    print('Fail to reject Null Hypothesis') #ie Null is Valid / True

Fail to reject Null Hypothesis


In [5]:
# t test - two sample -to determine difference between the mean of sample
#and population

In [4]:
#Independent Samples - t test compares the means of two inependent groups
#in order to determine whether the associated population means are significantly
#different. Independent Sample t test is a parametric test. this test is also
#known as independent t test

In [3]:
#Null Hypothesis: There is no difference between two Independent Sample Means
#Alternative Hypothesis: There is difference between two Independent Sample Means
#alpha value =5%

#p value < 0.05 Reject the null Hypothesis
#p value > 0.05 Fail to reject Null Hypothesis

In [17]:
np.random.seed(16)
classB_age=stats.poisson.rvs(loc=0,mu=33,size=100)

In [19]:
classB_age

array([28, 34, 31, 36, 34, 37, 28, 36, 28, 34, 30, 37, 38, 22, 21, 32, 36,
       29, 26, 30, 27, 30, 35, 37, 32, 32, 36, 34, 36, 25, 37, 30, 24, 34,
       32, 29, 42, 22, 44, 36, 32, 37, 27, 35, 29, 25, 44, 32, 35, 33, 25,
       17, 40, 36, 39, 27, 30, 28, 26, 36, 24, 31, 33, 42, 40, 25, 50, 34,
       30, 34, 42, 33, 31, 27, 31, 39, 30, 36, 30, 39, 38, 36, 39, 45, 33,
       34, 35, 38, 36, 27, 37, 27, 41, 26, 18, 27, 35, 25, 39, 34])

In [20]:
# Variance of Class B
classB_age.mean()

32.65

In [21]:
#Variance of Class A --> Variance are Unequal
classA_age.var()

37.7711

In [22]:
#Variance of Class B -- Variance are unequal
classB_age.var()

35.36750000000001

In [23]:
ttest,p_value=stats.ttest_ind(classA_age,classB_age,equal_var=False)

In [24]:
ttest

9.70756126806443

In [25]:
p_value

1.4984705862761275e-18

In [26]:
if p_value < 0.05:
    print('Reject Null Hypothesis')
else:
    print('Fail to reject Null Hypothesis')

Reject Null Hypothesis


In [27]:
# Paired t test
#when you want to check for how different samples from the same group are you can go for paired t test

In [28]:
#Null Hypothesis: There is no difference between two Dependent Sample Means
#(Before & After)
#Alternative Hypothesis: There is difference between two Dependent Sample Means
#alpha value =5%

#p value < 0.05 Reject the null Hypothesis
#p value > 0.05 Fail to reject Null Hypothesis

In [29]:
# Weight 1 at time t, weight 2 at time t+t1
weight1=[50,95,87,90,85,55,45,78,77,74]
weight2=weight1+stats.norm.rvs(scale=5,loc=1.25,size=10)

In [30]:
weight1

[50, 95, 87, 90, 85, 55, 45, 78, 77, 74]

In [31]:
weight2

array([55.67907026, 97.00171735, 88.2973866 , 82.27747659, 90.4619775 ,
       47.83574294, 45.8546287 , 77.57130145, 80.84624442, 78.78553199])

In [32]:
weight_df=pd.DataFrame({'weight10':np.array(weight1),
                      'weight20':np.array(weight2),
                      'weight_change':np.array(weight2)-np.array(weight1)})
weight_df

weight10   weight20  weight_change
0        50  55.679070       5.679070
1        95  97.001717       2.001717
2        87  88.297387       1.297387
3        90  82.277477      -7.722523
4        85  90.461978       5.461978
5        55  47.835743      -7.164257
6        45  45.854629       0.854629
7        78  77.571301      -0.428699
8        77  80.846244       3.846244
9        74  78.785532       4.785532

In [33]:
ttest,p_value=stats.ttest_rel(weight1,weight2)

In [34]:
p_value

0.5866507667638854

In [35]:
if p_value < 0.05:
    print('Reject Null Hypothesis')
else:
    print('Fail to reject Null Hypothesis')

Fail to reject Null Hypothesis
